services:
  - type: web
    name: ticket-system
    runtime: python
    region: frankfurt  # ou "oregon", "singapore" selon votre localisation
    buildCommand: |
      pip install -r requirements.txt
      python -c "from ticket_system_unified import init_db; init_db()"
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 ticket_system_unified:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ticketdb
          property: connectionString
      - key: ADMIN_PASSWORD
        sync: false  # À définir manuellement dans le dashboard
      - key: FLASK_ENV
        value: production
    healthCheckPath: /ping

databases:
  - name: ticketdb
    plan: free
    region: frankfurt  # Doit correspondre à la région du service web